### ISSUE TITLE
Peer list improvements

### ISSUE THREAD

**Issue by MayeulC** [yggdrasil-network/crispa-android#13]
Here are my issues:
* The peer list is cleaned when battery saver is (de)activated, or any time the screen is reloaded, for that matter (such as going back). Since the list takes a long time to get populated, it is quite annoying to have it clean every time you go back.
* The peer I select from the list gets unchecked as soon as the list is updated, which means I must wait for the scan to finish before selecting it
* The save button doesn't work before scanning is done, anyway.

A couple suggestions:
* Start pinging asynchronously, not sequentially. Probably a good use case for async/await. I think it should also be easier on battery.
* Cache the list and use it to speed-up bootstraping (start pinging before receiving a new list)

Of course, take your time if you have other stuff in mind first. These are just my first impressions.

**Comment by vikulin** [comment]
@MayeulC , please check it again. Most of issues fixed in v 1.6 (11) from https://t.me/yggdrasil_android. Open separate tickets for existing or new issues.
