### ISSUE TITLE
Problem with switching underlaying transport connection

### ISSUE THREAD

**Issue by jorektheglitch** [yggdrasil-network/crispa-android#19]
App do silently crash while switchin underlaying connection (e.g. while it disconnects from WiFi and connects to mobile network).

Steps to reproduce:
1) Start app
2) Choose peers
3) Start ygg (Turn on "Ygg me!")
4) Turn off and turn on Internet connection

After that app works as usually but Yggdrasil doesn't works.
Sometimes (after silent crash) app has double fully crash if user switches "Ygg me!" trigger.

**Comment by vikulin** [comment]
Fixed in v1.5

Closed.

**Comment by jorektheglitch** [comment]
It is actual again
