### ISSUE TITLE
1.4 is unstable compared to 1.3

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/crispa-android#26]
What makes it freeze, I don't know, but it freezes a lot. 1.3 isn't doing this.

Razer Phone 2, Android 9

**Comment by ChronosXYZ** [comment]
@styromaniac Hmm, thanks for report, I will investigate this. By the way, do you have any logs when it freezing?

**Comment by styromaniac** [comment]
I don't.

**Comment by styromaniac** [comment]
I'm back on 1.4. I'm not sure I was correct here saying 1.4 is less stable than 1.3.

**Comment by styromaniac** [comment]
1.5 seems good so far.
