### ISSUE TITLE
Show public key

### ISSUE THREAD

**Issue by davidadriao** [yggdrasil-network/crispa-android#30]
It would be usefull to show the public encryption key to send to peers so they can whitelist.

**Comment by vikulin** [comment]
@davidadriao , could you please advise what better variant to add it in UI?

**Comment by davidadriao** [comment]
A box similar to the one showing the IP address after connected would work nicely, with the copy button to easily share.

**Comment by whoizit** [comment]
![Screenshot_20201206-0258171](https://user-images.githubusercontent.com/359276/101268439-d3da5500-3773-11eb-9b25-fc4fadb76be5.jpg)
![Screenshot_20201206-0258381](https://user-images.githubusercontent.com/359276/101268437-d046ce00-3773-11eb-906c-3614c3274e02.jpg)

**Comment by vikulin** [comment]
Done. check in v 1.6 (11) from https://t.me/yggdrasil_android . 
![copy](https://user-images.githubusercontent.com/743622/101345383-a1257f00-388f-11eb-9b91-b44025999ce2.jpg)
