### ISSUE TITLE
High amount of peers hide the DNS settings

### ISSUE THREAD

**Issue by timas130** [yggdrasil-network/crispa-android#32]
So, if you add >20 peers, the DNS card will go down and eventually hide completely. Since it's not a scrollview (or whatever it's called), I can't see and click the edit button. Also, it can also hide some peers. 

![Screenshot_20201026-091126832 (1)](https://user-images.githubusercontent.com/20511387/97139536-c93ba180-176b-11eb-888a-07f8f749ae0d.jpg)

Possible solutions:
* Specify a limited amount of peers on the home screen.
* Make the home screen scrollable

(I don't know if it's already been reported somewhere, so I will show it here)

**Comment by vikulin** [comment]
There is no point to put so many peers. Closing this.

пн, 26 окт. 2020 г. в 08:38, timas130 <notifications@github.com>:

**Comment by zhoreeq** [comment]
Maybe application could display a warning when user adds more than 1 Internet peer? Because a mobile phone might become a relay for other peers and consume a lot of expensive bandwidth.

**Comment by vikulin** [comment]
The optimal number of peers can be ~3-5.

пн, 26 окт. 2020 г. в 09:07, George <notifications@github.com>:

**Comment by zhoreeq** [comment]
Not for a mobile phone, ask the developers about this. 

Not to say, the quality of such a relay will be very poor and the phone might randomly get very hot in your pocket.

**Comment by vikulin** [comment]
This is not related to the current issue, please file the new one if you
see problems with overheating.

пн, 26 окт. 2020 г. в 09:28, George <notifications@github.com>:

**Comment by vikulin** [comment]
Fixed in v 1.6 (16) from https://t.me/yggdrasil_android. Now the list has a max number of lines = 10. Closed.
