### ISSUE TITLE
Add some firewall to Yggdrasil app

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/crispa-android#34]
I'm no longer running the Yggdrasil ZeroNet tracker listed on the Yggdrasil Services webpage (clearnet). The reason is that China is hacking my phone, so I'm using NetGuard now.

https://github.com/M66B/NetGuard

My suggestion is to borrow the features or the code (license permitting, I hope) of NetGuard so I can have both Yggdrasil and a firewall running simultaneously. I would no longer have to compromise features nor security by having to choose one app over the other.

I wouldn't mind at all if Yggdrasil and NetGuard were merged into one app. That would be fantastic. In fact, that would help to grow the Yggdrasil network.

**Comment by vikulin** [comment]
VPN service is not under our control enough.  It should be implemented in https://github.com/yggdrasil-network/yggdrasil-go core. Please file the issue in mentioned repo.
