### ISSUE TITLE
Peers list doesn't seem to be saved

### ISSUE THREAD

**Issue by EternityForest** [yggdrasil-network/crispa-android#35]
It seems that there is no way to add a peer, because the save button doesn't do anything.   Am I doing something wrong?

**Comment by vikulin** [comment]
Can you take a screenshot with new peer form?

**Comment by EternityForest** [comment]
After some more digging, I think I found my answer in issue #13, the save button only works when scanning is totally finished, and that takes a minute or so, and restarts if you leave the page.

**Comment by vikulin** [comment]
see details how peer saving works now in #36
