### ISSUE TITLE
Add an option to specify a custom peer list URL

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-network/crispa-android#36]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7319#note_456869833

F-Droid shows anti-feature badge because users can't set their own peer list URL

**Comment by zhoreeq** [comment]
Seems like the DNS server list is also locked to a single "vendor" and cannot be replaced with a custom list

**Comment by jorektheglitch** [comment]
You can add your cusyom DNS manually

**Comment by zhoreeq** [comment]
@jorektheglitch read carefully, DNS server **list**

**Comment by vikulin** [comment]
@zhoreeq , I could add IPv6 DNS address as well. See the screenshot:
![DNS](https://user-images.githubusercontent.com/743622/101279753-1d0ac300-37cd-11eb-92fc-da6b4e886bc1.jpg)

Please check the issue in v 1.5 and reopen if needed.

**Comment by zhoreeq** [comment]
It is v1.5 issue indeed. I cannot reopen the issue, why did you close it?

**Comment by vikulin** [comment]
@zhoreeq , fixed in v 1.6. Please check it. See https://t.me/yggdrasil_android
