### ISSUE TITLE
Rebuild with updated yggdrasil-extras

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/crispa-android#38]
yggdrasil-network/yggdrasil-extras@b91e022 contains fixes present in `yggdrasil-develop-0.3.15-0087` so that IPv6 internet traffic that is erroneously sent to the dummy adapter will generate an ICMPv6 Destination Unreachable response. This will hopefully mean that running Yggdrasil will no longer cause some applications to incorrectly hang for some time trying IPv6 internet connectivity when there is none.

Please update the Android build accordingly by generating a new `.aar`:
```
cd /path/to/yggdrasil-go
git checkout develop
git pull origin develop
go get github.com/yggdrasil-network/yggdrasil-extras@b91e022
./build -a
```

**Comment by vikulin** [comment]
Done. Check v 1.6 (14) from https://t.me/yggdrasil_android .

**Comment by styromaniac** [comment]
This works. MeWe doesn't have anymore problems.
