### ISSUE TITLE
Any GUI screenshots?

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-network/crispa-android#4]
Would be nice to see application screenshots in README.md

**Comment by kylerchin** [comment]
![Screenshot from 2020-06-14 14-50-55](https://user-images.githubusercontent.com/7539174/84604969-83321100-ae4e-11ea-92ca-e02da0b29277.png)
![Screenshot from 2020-06-14 14-50-19](https://user-images.githubusercontent.com/7539174/84604971-85946b00-ae4e-11ea-8f79-56aca6bffd0f.png)

**Comment by kylerchin** [comment]
Is that ok?

**Comment by kylerchin** [comment]
![Screenshot_1592171817](https://user-images.githubusercontent.com/7539174/84605129-cb9dfe80-ae4f-11ea-920f-cb0a8a02dbe7.png)
![Screenshot_1592171966](https://user-images.githubusercontent.com/7539174/84605130-ce005880-ae4f-11ea-942f-da2487cd9942.png)
![Screenshot_1592172072](https://user-images.githubusercontent.com/7539174/84605155-03a54180-ae50-11ea-9637-d9a299093743.png)

**Comment by kylerchin** [comment]
https://github.com/ChronosX88/yggdrasil-android/pull/5

**Comment by ChronosXYZ** [comment]
> 
> 
> #5

@kylerchin Need to update screenshots due to new app design.

**Comment by MayeulC** [comment]
Please don't add these screenshots to the repository, that would make it huge and slow to download. Links to external screenshots (like these here) are fine, though. And I noticed that's what is being done now, which is good IMO.

I wish the same was done for the yggdrasil binary (not sure what the current state is).

Side note: these are on the huge side, they take up more than one screen of vertical real estate. I'd prefer there to be multiple ones side-by-side.

**Comment by vikulin** [comment]
@ChronosX88 , please update screenshots. http://wiki.yggdrasil.link/doku.php?id=yggdrasil:mobile_clients contains the latest one and small size pictures.

**Comment by ChronosXYZ** [comment]
Resolved in https://github.com/yggdrasil-network/yggdrasil-android/commit/c9dd3dcd8116d5dd4bfbf929ac6afc39da7ec68e.
