### ISSUE TITLE
tag new release on main repo

### ISSUE THREAD

**Issue by 6543** [yggdrasil-network/crispa-android#40]
@vikulin for F-Droid to pickup the new release you have to push the tag here too ...

-> https://github.com/vikulin/yggdrasil-android/releases/tag/v1.6

**Comment by vikulin** [comment]
Are you sure that the repo can be mine not the parent from yggdrasil-network?

**Comment by 6543** [comment]
Sorry I dont understand the question...

Do you suggest to use your fork as "official" git repo?

**Comment by vikulin** [comment]
No, I mean I'm not sure F-Droid can pick up the fork repo.

**Comment by vikulin** [comment]
I think the tag will be automatically seted up after new release is published. Please reopen the issue in that case
