### ISSUE TITLE
.ygg domains don't resolve.

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/crispa-android#44]
Version: yggdrasil-android-1.6-release.apk
OS: Android 9
Device: Razer Phone 2

**Comment by vikulin** [comment]
Please share more info such as:
1. DNS you are using in Yggdrasil
2. Web browser version
3. Web site address (full domain name)

**Comment by styromaniac** [comment]
1. [303:8b1a::53]
2. Firefox 84.1.4 and Chrome 87.0.4280.101
3. http://sites.ygg/

**Comment by vikulin** [comment]
this is the DNS temporal issue:

![sites](https://user-images.githubusercontent.com/743622/104096239-f516ef80-52a3-11eb-8818-9c85164eed69.jpg)
