### ISSUE TITLE
Нет доступных DNS (ошибка) 

### ISSUE THREAD

**Issue by chicago666666** [yggdrasil-network/crispa-android#46]
![Screenshot_20210112-190323](https://user-images.githubusercontent.com/20189080/104347078-debd9d80-5508-11eb-9474-b7ffc4ac242c.png)
После нажатия на "edit" появляется такое уведомление.
Android 7
Samsung galaxy tab T705

**Comment by vikulin** [comment]
DNS можно выбрать после включения кнопки Ygg me!

**Comment by chicago666666** [comment]
![Screenshot_20210112-191146](https://user-images.githubusercontent.com/20189080/104348252-2abd1200-550a-11eb-8818-70674b7c7915.png)
Так нет же! Вот со включенной кнопкой Ygg me!

**Comment by vikulin** [comment]
У вас стоит Airplane режим и не активирован VPN. Без этого Yggdrasil сервис не работает.
