### ISSUE TITLE
Не решёная проблема с DNS

### ISSUE THREAD

**Issue by chicago666666** [yggdrasil-network/crispa-android#47]
![Screenshot_20210112-202343](https://user-images.githubusercontent.com/20189080/104356313-783e7c80-5514-11eb-8f19-b379c8ee20fc.png)
![Screenshot_20210112-202231](https://user-images.githubusercontent.com/20189080/104356326-7e345d80-5514-11eb-84d5-0f44133a3efb.png)

1. Без полёта, без всё
2. Без полёта, с впн!

Не спеши закрывать тему пожалуйста, раньше чем эта штука заработает!
Если по твоему решение так очевидно, то возможно стоит добавить в программу какую-то справку? Подсказки, советы!?

**Comment by vikulin** [comment]
2. У вас запущено приложение, использующее VPN? Если да, то его нужно остановить прежде чем запускать Ygg me!

**Comment by vikulin** [comment]
Справка доступна если нажать на VERSION

**Comment by chicago666666** [comment]
1. Впн отключен!
2. ... конечно я видел VERSION... Там есть ответ на мой вопрос: почему доступен список Peer и не доступен список DNS ?
2.2 ... Английский язык это конечно хорошо (я тоже понимаю более менее), но вы же русский человек! ) Для земляков можно же вкладку сделать?)

Не суть. В общем программа не работает, ошибка та же! Впн выключен, "полёт" тоже выключен.
Что ещё может?

**Comment by chicago666666** [comment]
![Screenshot_20210112-224525](https://user-images.githubusercontent.com/20189080/104370806-125bf000-5528-11eb-9a51-73e24c8551a5.png)
Перечитал VERSION - лишний пробел в слове  "It"

**Comment by vikulin** [comment]
Давайте решать проблемы со справкой отдельно. Видимо, придется вновь пересказывать, то что я неоднократно говорил: это свободное ПО, здесь нет прямых обязательств разработчиков перед пользователем и ваше "Для земляков можно же вкладку сделать?)" обретает некорректную форму. 
Во-первых: справкой я занялся уже тогда когда стало понятно, что этим никто из сообщества разработчиков или пользователей заниматься не хочет.
Во-вторых: давайте по порядку. Опишите конфигурацию на которой вы запускаете приложение: модель устройства, версию Андроид
В третих: если вы понимаете английский на достаточном уровне, то оформляйте на нём дефекты на гитхаб так как программа не только для русскоязычной аудитории.

**Comment by vikulin** [comment]
На первом скриншоте у вас работает VPN, убедитесь, еще раз, что его не использует другое приложение.

**Comment by chicago666666** [comment]
Уважаемый разработчик!
Не о каких обязательствах нет и речи! Самое бесценное для каждого человека - это время! Вы потратили своё время жизни на создание продукта и Я почему-то уверен, что Вы хотите чтобы он работал исправно! В свою очередь я потратил своё личное время на то чтобы сообщить о неисправности, обнаружил незначительную погрешность в тексте "справки" и абсолютно без претензий сообщил о них! Только для того чтобы дело жило! Мне с этого деньги не капнут так что о каком оформлении дефектов на гитхаб может идти речь (на английском языке), если наши не настолько грамотные земляки не поймут о чём речь, если столкнуться с подобной проблемой? )
Samsung galaxy tab t705, Android 7 Resurrection Remix, +root

**Comment by chicago666666** [comment]
![Screenshot_20210113-164837](https://user-images.githubusercontent.com/20189080/104467810-69f96a80-55bf-11eb-8e4f-38f5620b5882.png)
Даже когда VPN отключен Yggdrasil не подключается из-за этого "постоянный ВПН".
![Screenshot_20210113-164801](https://user-images.githubusercontent.com/20189080/104468083-b9d83180-55bf-11eb-965b-4f565492dcd0.png)
Теперь всё работает как надо!
![Screenshot_20210113-164743](https://user-images.githubusercontent.com/20189080/104468168-cfe5f200-55bf-11eb-8715-797cd822fc52.png)

**Comment by vikulin** [comment]
Отично!
