### ISSUE TITLE
Multicast doesn't work

### ISSUE THREAD

**Issue by vantu5z** [yggdrasil-network/crispa-android#62]
Yddrasil docs says that local peers (in the same network) should discovered automatically.
But after enabling "ygg me!" - I don't see connected peer to my PC (Arch Linux) by `sudo yggdrasilctl getpeers` and also can't ping it by ipv6. But if I add some public peers - I can ping phone by ipv6 and make ssh connections from both sides.
Firewall is disabled on PC.

**Smartphone:**
 - Device: Redmi Note 10S
 - OS: Android 11

**Additional context**
crispa-android - 2.0.19
yggdrasil - 0.4.3-1 (Arch Linux)

**Comment by vikulin** [comment]
Check it for recent build

**Comment by vikulin** [comment]
v 2.1.2 is recent release build.
