### ISSUE TITLE
Yggdrasil Extras is deprecated

### ISSUE THREAD

**Issue by marek22k** [yggdrasil-network/crispa-android#63]
> This package is now deprecated and all resources have been moved into the main Yggdrasil repository under contrib/mobile. Please use that from now on.
https://github.com/yggdrasil-network/yggdrasil-extras

moved to https://github.com/yggdrasil-network/yggdrasil-go/tree/develop/contrib/mobile

maybe you can link it to the new repo?

**Comment by vikulin** [comment]
Done. Migrated to mobile package and removed extras.
