### ISSUE TITLE
I need to be able to use NextDNS to access my Handshake domain.

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/crispa-android#69]
http://y.styromaniac.creator/ points to my Yggdrasil  site.

**Comment by vikulin** [comment]
Use (+) button to add a DNS.

**Comment by styromaniac** [comment]
I've already done that. It doesn't work when I've entered NextDNS IP addresses.

Edit: I had to turn off private DNS.

**Comment by vikulin** [comment]
Write your ip dns here please.

Ср, 29 июня 2022 г. в 20:08, Styromaniac ***@***.***>:

**Comment by styromaniac** [comment]
We're good.  I figured out the problem.
