### ISSUE TITLE
Tell the user that they have to turn off Private DNS

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/crispa-android#70]
Some of us had thought that the DNS feature of your app was not working or not exactly what we're looking for, but it is and it's the Private DNS feature getting in the way.

**Comment by vikulin** [comment]
Actually I shouldn’t. This is Android functionality scope. But you always
may create a PR and write down it to FAQ.

Ср, 29 июня 2022 г. в 20:20, Styromaniac ***@***.***>:
