### ISSUE TITLE
Ygg app as a proxy

### ISSUE THREAD

**Issue by accfm** [yggdrasil-network/crispa-android#71]
Hello!
Is it possible to add the option to connect to Ygg->Internet proxy via application and pass all traffic from the device through this proxy?
Beleive this would be a great opportunity in some cases.

**Comment by vikulin** [comment]
This definitely not a priority. Proxy is an application level. I have no intention to mix networking level with proxy. You can run http proxy server on Android as a separate app. I’m sure there are a lot.
