### ISSUE TITLE
Allow local DNS

### ISSUE THREAD

**Issue by EchedelleLR** [yggdrasil-network/crispa-android#73]
I currently use personalDNSFilter which allows local DNS without VPN.

However, this applications doesn't allow me to point to my local DNS server which is also over a custom port and just allows me IPV6 based ones over the Yggdrasil network AFAIS.

Could support for this be added?

**Comment by vikulin** [comment]
IPv4 DNS server can’t be added in Ygg app since this is only ipv6 capable.
Consider Android DNS specific settings setup.

Пн, 19 сент. 2022 г. в 00:57, EchedeyLR ***@***.***>:

**Comment by vikulin** [comment]
Closing.

**Comment by EchedelleLR** [comment]
Android DNS specific settings are for DoT only as for Android 11 as maximum and not allowed below 8 or 9.

It also doesnt help if the app is not capable of providing an endpoint for it, which has no sense in a local setup at all for which another developer will throw a wontfix too.

**Comment by vikulin** [comment]
Why not to setup ipv6 address for local DNS and point it from crisps?

Пн, 19 сент. 2022 г. в 02:03, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
?

It doesn't allow me to setup local DNS directly, being either IPv6 or IPv4. At least not with custom port.

I also tried some tweaks in how to set the IPv6 to local one with custom port but Yggdrasil either finished not adding it or crashed.

**Comment by EchedelleLR** [comment]
Following other format definition as I am not familiar at all on how are IP plus port defined here for IPv6 (I already experimented differences in implementations in different applications because of parsing issues for IPv6) and tried `::1::5300` and the app just crashed.

So, even if this is up for a bug report, I was unsure if this was related, I was too dumb to understand the format  or if it simply was not supported so I finished guessing that was not supported and reported as normal.

**Comment by vikulin** [comment]
Give me the error you are seeing when you add ipv6 local DNS.

Пн, 19 сент. 2022 г. в 09:46, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
First things first, is the correct format the one I posted as example or is it not?

**Comment by EchedelleLR** [comment]
Anyways, here is the screenshot. No error code, direct crash.

![Screenshot_20220919-075311_Yggdrasil](https://user-images.githubusercontent.com/56733813/190963776-a7c29506-1c84-4095-9c6e-a28d0bc2e0e1.png)

**Comment by vikulin** [comment]
What DNS address you are entering?

Пн, 19 сент. 2022 г. в 09:54, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
I said it in the previous of the previous of that message and later asked, after your reply, if that was the proper format.

**Comment by vikulin** [comment]
That address format is incorrect, should surrounded with square brackets
without port.

Пн, 19 сент. 2022 г. в 10:04, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
As far as I saw in the self-pointed dynamic list which takes ages to load, the format seems to be ` ::1::5300` being apparently the last 2 colons for the port.

**Comment by EchedelleLR** [comment]
Port is needed because it is a custom port. Setting a port below 1024 requires root privileges.

**Comment by EchedelleLR** [comment]
I am not allowed to put brackets in that field...

**Comment by vikulin** [comment]
Android VPN config does not allow to setup custom port for DNS. Also it
does not allow port forwarding requiring root in device. I recommend to
setup iptables port forwarding which will solve you service root privileges
issue.

Пн, 19 сент. 2022 г. в 10:09, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
But does not iptables require root privileges on Android, is it even possible to use it?

**Comment by vikulin** [comment]
This is out of scope of the project since custom DNS port is quite rare
case. Anyway iptables solution should work for you.
Пн, 19 сент. 2022 г. в 10:15, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
All local DNS apps which allow you to use them without VPN mode do it if not in root privileges.

Also, would you reply to my question before? Are root privileges needed for Iptables on Android or is something I can figure out in other way?

**Comment by vikulin** [comment]
Iptables shoul be configured on the host where a custom DNS port is
running. Then you won’t need to run service from root. Iptables is still
requiring root but it’s a good compromise.

Пн, 19 сент. 2022 г. в 10:17, Vadym Vikulin ***@***.***>:

**Comment by EchedelleLR** [comment]
Then we are in a loop.

The DNS filter runs on phone, which cannot get root privileges because of capability limitation not because a security rule I set and runs custom port.

Then, VPN doesn't allow custom port because of another capability limitation.

 Iptables is a solution but requires root privileges.

**Comment by vikulin** [comment]
This not a loop. You can setup iptables on DNS service side.

Пн, 19 сент. 2022 г. в 10:27, EchedeyLR ***@***.***>:

**Comment by vikulin** [comment]
DNS should run on another host allowing port forwarding. It can be your
network router. It can redirect back DNS port to your phone with custom
value ie phone ip:53->router ip:53->phone ip:5353

Пн, 19 сент. 2022 г. в 10:30, Vadym Vikulin ***@***.***>:

**Comment by EchedelleLR** [comment]
This would not work on mobile network and I would lose custom DNS capabilities.

The idea of having DNS on phone as many apps allow is that, that you are not dependent of the network you are connected to.

In my case I use OpenNIC and for adblock capabilities.

**Comment by EchedelleLR** [comment]
I dont have access to every router in every network (which is impossible unless you don't use your phone as a phone but as a portable computer wired in every place you go), and that is not even possible in a mobile network.

**Comment by vikulin** [comment]
Yep, this is Android limitations. Try to use Ubuntu Touch. This is untested
by me but you would have much more freedom there.

Пн, 19 сент. 2022 г. в 11:48, EchedeyLR ***@***.***>:

**Comment by EchedelleLR** [comment]
Thank you @vikulin for the help and the explanations.

I am sorry if dealing with me was a bit annoying.

**Comment by vikulin** [comment]
Crispa does not allow to use DNS without VPN, also iptables requires root
on Android as well.

Пн, 19 сент. 2022 г. в 10:20, EchedeyLR ***@***.***>:
