### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kylerchin** [yggdrasil-network/crispa-android#8]
1. Material Design UI, the current UI is low key gross, maybe I can help?

2. The app exits on the second time I try to connect:
https://youtu.be/JGJ8Rxhepqg

3. Can we split the functions for generating a new configuration and connecting? that way, if I want a new IP, I can simply click "New config" or something?

**Comment by vikulin** [comment]
1. Done
2,3 fixed in 1.1

@ChronosX88 can be closed.
