### ISSUE TITLE
Crash on the launch

### ISSUE THREAD

**Issue by JeanPaulLucien** [yggdrasil-network/crispa-android#83]
**Describe the bug**

**To Reproduce**
1. Try to launch the app

**Expected behavior**
The app works.

**Screenshots**
Error in the app.

**Smartphone (please complete the following information):**
 - Device: Wexler Tab 7T + 3G
 - OS: Android 4.2.2
 
**Additional context**

**Comment by vikulin** [comment]
@JeanPaulLucien can you please clear up app cache and try to reproduce again?

**Comment by JeanPaulLucien** [comment]
> @JeanPaulLucien can you please clear up app cache and try to reproduce again?

I have got this issue at 1st time. I just installed the app from F-Droid.

**Comment by JeanPaulLucien** [comment]
```
WARNING,dalvikvm,Unknown,VFY: unable to resolve virtual method 719: Landroid/content/Context	.getNoBackupFilesDir ()Ljava/io/File
WARNING,dalvikvm,Unknown,VFY: unable to resolve direct method 180: Landroid/media/MediaCodecList	.<init> (I)V
WARNING,dalvikvm,Unknown,VFY: unable to resolve virtual method 238: Landroid/os/StatFs	.getBlockSizeLong ()J
WARNING,dalvikvm,Unknown,VFY: unable to resolve virtual method 238: Landroid/os/StatFs	.getBlockSizeLong ()J
WARNING,dalvikvm,Unknown,Unable to resolve superclass of Lorg/acra/sender/JobSenderService	-89
```
This is logs. I'm not sure that it's Yggdrasil (no process). Here I tried to launch the app.

**Comment by vikulin** [comment]
F-droid is unofficial source for yggdrasil crispa. Use github apk binary from releases.

**Comment by JeanPaulLucien** [comment]
@vikulin , same result, same logs. As expected.

**Comment by vikulin** [comment]
check the new binary:
https://github.com/yggdrasil-network/crispa-android/releases/tag/v2.1.5

**Comment by vikulin** [comment]
Final fix https://github.com/yggdrasil-network/crispa-android/releases/tag/v2.1.6
