### ISSUE TITLE
Disconnect / Connect causes app to crash

### ISSUE THREAD

**Issue by andrewheadricke** [yggdrasil-network/crispa-android#9]
I just got around to compiling this and it works great, well done @ChronosX88 and contributors.

I noticed if I try disconnect / connect a few times it crashes, it looks like maybe closing the app and re-opening it doesn't restore the current VPN status correctly.

**Comment by ChronosXYZ** [comment]
Thank you for your review, this issue is known and will be fixed soon! :)

**Comment by vikulin** [comment]
Fixed in https://github.com/vikulin/yggdrasil-extras/. Corresponding [pool request](https://github.com/yggdrasil-network/yggdrasil-extras/pull/8) https://github.com/yggdrasil-network/yggdrasil-extras/pull/8 has been created. But Nail is still looking into it.

**Comment by vikulin** [comment]
@ChronosX88 , can be closed. Fixed in 1.2
