### ISSUE TITLE
Rewrite function private fun hasIpv6DefaultRoute(): Boolean

### ISSUE THREAD

**Issue by JeanPaulLucien** [yggdrasil-network/crispa-android#93]
Seems it's wrong algoritm.
This function is false always for Android below Lolipop.
Algorithm to get true is incorrect. You get 1st true.

**Comment by JeanPaulLucien** [comment]
Also I suspect that the app does not use this function. Try to deleted.

**Comment by vikulin** [comment]
@JeanPaulLucien yes, it's used.
